# tell yaml plugin that this is the config file and not a template of its own:
# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
    - name: ğŸ™ Get Help
      url: https://github.com/polyfrost/nexus/discussions/new?category=help
      about: If you can't get something to work the way you expect, open a question in our discussion forums.
    - name: ğŸ’¡ Feature Request
      url: https://github.com/polyfrost/nexus/discussions/new?category=ideas
      about: Suggest any ideas you have using our discussion forums.
    - name: ğŸ’¬ Discord Chat
      url: https://polyfrost.cc/discord
      about: Ask questions and talk to other Polyfrost product users and the devs.
